language: cpp
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - build-essential
    - gawk
    - ccache
    - genromfs
    - libc6-i386
    - python-pip
    - python-dev
    - zlib1g-dev
    - gcc-4.9
    - g++-4.9
    - cmake
    - cmake-data
cache:
  ccache: true
  directories:
  - $HOME/opt
before_install:
- Tools/scripts/configure-ci.sh
- if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then export CI_CRON_JOB=1 ; fi
script:
- python Tools/autotest/param_metadata/param_parse.py
- Tools/scripts/build_ci.sh
before_cache:
- ccache -z
compiler:
- gcc
env:
  - CI_BUILD_TARGET="px4-v2-solo"
  - CI_BUILD_TARGET="linux"
  - CI_BUILD_TARGET="sitl"
  - CI_BUILD_TARGET="sitltest"
matrix:
  fast_finish: true
deploy:
  provider: releases
  api_key:
    secure: kY8zURHsBSBKKfioEXoV83OeIry4kOMTW+y3aKSPtRN589LgXGYF5sW68d8fsAM3lVXt6w3HmIwykvmwYoBWi2L0pYNT2WV7QXdwFp7BMwZTNoU5CL9qlBjYL7PH1LwFZuy26TVlvv/JVdoe7uXp4vODK4cFfbR57uwWC0EiOvU0hlOslukbZ52weC8xEgttT0Pi+jmjBwxwDkmM3yDyoMI1SDXA/oHhrpqCMXQ+vfIHqVQ1g5p/rLKakqxmbEMyYT3v6H2+j5jaOEj8wfeCso0omRdKsAwC2I6uWfLmeHtssCEBelRI6yyBmh30WoCFm6GtUGNsPIO9eFaRwPNANeWbSQVOqgGVJxxpbiPsPaAESAXVST2+PMObWDN457JPEgJhcj7N9IeOMgZox8CCaUoV6246eixt+5kZH6L1BZOpU1GXxdJdeXyAnk19z0TT/OrTONCVHep2KqbaJn6LxL/HidkKKFzK86J2HeDT3KRog0Zug7zhT7Bym5pAHeGnrSCkPRVtqxSg+atQ297xhSWYE482OUFo6wkZnLEI2zWY9Q73uR+40Zv7Llkiro+2I9QGWUOAKC738+kWkAwg17zKHn7W4WxiiZUw8y6gkI6NGuDM1rJ1ab+io8gzAIK/bTySWfDciQbzvB6X9wPClWUkqQhAWkuZdk6lC7MnYVI=
  file: 'ArduCopter/ArduCopter-v2.px4'
  skip_cleanup: true
  on:
    condition: $CI_BUILD_TARGET = px4-v2-solo
    repo: 3drobotics/ardupilot
    tags: true
